spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sync_async
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: false
    hibernate:
      id:
        new:
          new_generator_mappings: true
    showSql: true
    databases: mysql
    generate-ddl: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/sync_async
    username: root
    password:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
#  data:
#    r2dbc:
#      repositories:
#        enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/sync_async
#    username: root
#    password:
#    hikari:
#      connectionTimeout: 30000
#      maximumPoolSize: 5
#      maxLifetime: 1800000
#      poolName: HikariCP
#      readOnly: false
#      connectionTestQuery: SELECT 1
